[project]
name = "eventsaggregator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "oma", email = "oma@dk-sp.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic-settings>=2.15.0",
    "asyncpg>=0.31.0",
    "sqlalchemy[asyncio]>=2.0.0",
    "fastapi>=0.143.0",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
eventsaggregator = "eventsaggregator:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
